<div class="text-center footer">
    
       <div class="row ml-5 mt-5">
        <a class="lien nav-link col-1" aria-current="page" href="index.php">Accueil</a>
        <a class="lien nav-link col-1" href="apropos.php">A propos</a>
        <a class="lien nav-link col-1" href="contact.php">Contact</a>
       </div>
<p class="text-white">Copyright <i class="fa fa-copyright text-white" aria-hidden="true"></i>  2021</p>
</div>
</body>
</html>